// Generated from Pharmacy main at 5b4f7d2443a3ed97aea752c1d0d18583ce6d0067; do not edit by hand.
import type { PharmacyProductCatalogEntry } from './pharmacyProductCatalog';

export const PHARMACY_PRODUCT_CATALOG: PharmacyProductCatalogEntry[] = [
  {
    "id": "prod-panadol-500",
    "documentId": "doc-product-prod-panadol-500",
    "brandName": "Panadol 500mg",
    "genericName": "Paracetamol",
    "activeIngredients": "Paracetamol 500mg per tablet",
    "packSize": "20 Tablets",
    "schedule": "Unscheduled",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-1",
    "subcategoryFa": "ضد درد و تب (Analgesics & Antipyretics)",
    "subcategoryEn": "Analgesics & Antipyretics",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-panadol-osteo",
    "documentId": "doc-product-prod-panadol-osteo",
    "brandName": "Panadol Osteo 665mg",
    "genericName": "Paracetamol (Modified Release)",
    "activeIngredients": "Paracetamol 665mg modified release tablet",
    "packSize": "96 Modified Release Tablets",
    "schedule": "S2",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-1",
    "subcategoryFa": "ضد درد و تب (Analgesics & Antipyretics)",
    "subcategoryEn": "Analgesics & Antipyretics",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-nurofen-200",
    "documentId": "doc-product-prod-nurofen-200",
    "brandName": "Nurofen 200mg",
    "genericName": "Ibuprofen",
    "activeIngredients": "Ibuprofen 200mg per capsule",
    "packSize": "24 Liquid Capsules",
    "schedule": "S2",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-1",
    "subcategoryFa": "ضد درد و تب (Analgesics & Antipyretics)",
    "subcategoryEn": "Analgesics & Antipyretics",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-voltaren-rapid-25",
    "documentId": "doc-product-prod-voltaren-rapid-25",
    "brandName": "Voltaren Rapid 25",
    "genericName": "Diclofenac Potassium",
    "activeIngredients": "Diclofenac potassium 25mg tablet",
    "packSize": "30 Tablets",
    "schedule": "S2",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-1",
    "subcategoryFa": "ضد درد و تب (Analgesics & Antipyretics)",
    "subcategoryEn": "Analgesics & Antipyretics",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-nuromol-tablets",
    "documentId": "doc-product-prod-nuromol-tablets",
    "brandName": "Nuromol Tablets",
    "genericName": "Paracetamol + Ibuprofen",
    "activeIngredients": "Paracetamol 500mg + Ibuprofen 200mg",
    "packSize": "24 Tablets",
    "schedule": "S3",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-1",
    "subcategoryFa": "ضد درد و تب (Analgesics & Antipyretics)",
    "subcategoryEn": "Analgesics & Antipyretics",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-aspirin-300",
    "documentId": "doc-product-prod-aspirin-300",
    "brandName": "Aspro Clear 300mg",
    "genericName": "Aspirin (Soluble / Effervescent)",
    "activeIngredients": "Aspirin 300mg effervescent tablet",
    "packSize": "24 Soluble Tablets",
    "schedule": "Unscheduled",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-1",
    "subcategoryFa": "ضد درد و تب (Analgesics & Antipyretics)",
    "subcategoryEn": "Analgesics & Antipyretics",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-diflucan-150",
    "documentId": "doc-product-prod-diflucan-150",
    "brandName": "Diflucan One 150mg",
    "genericName": "Fluconazole",
    "activeIngredients": "Fluconazole 150mg capsule",
    "packSize": "1 Oral Capsule",
    "schedule": "S3",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-2",
    "subcategoryFa": "داروهای ضد قارچ و ضد انگل (Antifungals & Anthelmintics)",
    "subcategoryEn": "Antifungal & Anthelmintic Agents",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-canesten-cream",
    "documentId": "doc-product-prod-canesten-cream",
    "brandName": "Canesten Topical Cream 1%",
    "genericName": "Clotrimazole",
    "activeIngredients": "Clotrimazole 10mg/g (1%)",
    "packSize": "20g Tube",
    "schedule": "S2",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-2",
    "subcategoryFa": "داروهای ضد قارچ و ضد انگل (Antifungals & Anthelmintics)",
    "subcategoryEn": "Antifungal & Anthelmintic Agents",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-lamisil-cream",
    "documentId": "doc-product-prod-lamisil-cream",
    "brandName": "Lamisil Cream 1%",
    "genericName": "Terbinafine Hydrochloride",
    "activeIngredients": "Terbinafine HCl 10mg/g (1%)",
    "packSize": "15g Tube",
    "schedule": "S2",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-2",
    "subcategoryFa": "داروهای ضد قارچ و ضد انگل (Antifungals & Anthelmintics)",
    "subcategoryEn": "Antifungal & Anthelmintic Agents",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-loceryl-nail-lacquer",
    "documentId": "doc-product-prod-loceryl-nail-lacquer",
    "brandName": "Loceryl Nail Lacquer 5%",
    "genericName": "Amorolfine",
    "activeIngredients": "Amorolfine 5% w/v nail lacquer",
    "packSize": "5 mL Bottle with Applicator & Files",
    "schedule": "S2",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-2",
    "subcategoryFa": "داروهای ضد قارچ و ضد انگل (Antifungals & Anthelmintics)",
    "subcategoryEn": "Antifungal & Anthelmintic Agents",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-combantrin-choc-squares",
    "documentId": "doc-product-prod-combantrin-choc-squares",
    "brandName": "Combantrin Chocolate Squares",
    "genericName": "Pyrantel Embonate",
    "activeIngredients": "Pyrantel embonate equivalent to 100mg pyrantel per square",
    "packSize": "24 Chocolate Squares",
    "schedule": "Unscheduled",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-2",
    "subcategoryFa": "داروهای ضد قارچ و ضد انگل (Antifungals & Anthelmintics)",
    "subcategoryEn": "Antifungal & Anthelmintic Agents",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-vermox-tablets",
    "documentId": "doc-product-prod-vermox-tablets",
    "brandName": "Vermox 100mg Tablets",
    "genericName": "Mebendazole",
    "activeIngredients": "Mebendazole 100mg chewable tablet",
    "packSize": "6 Chewable Tablets",
    "schedule": "S2",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-2",
    "subcategoryFa": "داروهای ضد قارچ و ضد انگل (Antifungals & Anthelmintics)",
    "subcategoryEn": "Antifungal & Anthelmintic Agents",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-lyclear-scabies-cream",
    "documentId": "doc-product-prod-lyclear-scabies-cream",
    "brandName": "Lyclear Scabies Cream 5%",
    "genericName": "Permethrin",
    "activeIngredients": "Permethrin 5% w/w cream",
    "packSize": "30g Tube",
    "schedule": "S2",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-2",
    "subcategoryFa": "داروهای ضد قارچ و ضد انگل (Antifungals & Anthelmintics)",
    "subcategoryEn": "Antifungal & Anthelmintic Agents",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-chlorsig-eye-drops",
    "documentId": "doc-product-prod-chlorsig-eye-drops",
    "brandName": "Chlorsig 0.5% Eye Drops",
    "genericName": "Chloramphenicol",
    "activeIngredients": "Chloramphenicol 5mg/mL (0.5%)",
    "packSize": "10 mL Dropper Bottle",
    "schedule": "S3",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-3",
    "subcategoryFa": "بیماری‌های چشم و گوش (Eye & Ear Conditions)",
    "subcategoryEn": "Eye & Ear Conditions",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-systane-ultra-drops",
    "documentId": "doc-product-prod-systane-ultra-drops",
    "brandName": "Systane Ultra Lubricant Eye Drops",
    "genericName": "Polyethylene Glycol + Propylene Glycol",
    "activeIngredients": "PEG-400 0.4% + Propylene glycol 0.3% + HP-Guar",
    "packSize": "10 mL Dropper Bottle",
    "schedule": "Unscheduled",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-3",
    "subcategoryFa": "بیماری‌های چشم و گوش (Eye & Ear Conditions)",
    "subcategoryEn": "Eye & Ear Conditions",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-zaditen-eye-drops",
    "documentId": "doc-product-prod-zaditen-eye-drops",
    "brandName": "Zaditen Eye Drops 0.025%",
    "genericName": "Ketotifen Fumarate",
    "activeIngredients": "Ketotifen fumarate 0.25mg/mL",
    "packSize": "5 mL Bottle",
    "schedule": "S2",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-3",
    "subcategoryFa": "بیماری‌های چشم و گوش (Eye & Ear Conditions)",
    "subcategoryEn": "Eye & Ear Conditions",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-waxsol-ear-drops",
    "documentId": "doc-product-prod-waxsol-ear-drops",
    "brandName": "Waxsol Ear Drops",
    "genericName": "Docusate Sodium (Otic)",
    "activeIngredients": "Docusate sodium 0.5% w/v",
    "packSize": "10 mL Dropper Bottle",
    "schedule": "Unscheduled",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-3",
    "subcategoryFa": "بیماری‌های چشم و گوش (Eye & Ear Conditions)",
    "subcategoryEn": "Eye & Ear Conditions",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-aqua-ear-drops",
    "documentId": "doc-product-prod-aqua-ear-drops",
    "brandName": "Aqua Ear Solution",
    "genericName": "Acetic Acid + Isopropyl Alcohol",
    "activeIngredients": "Acetic acid 1.73% + Isopropyl alcohol 63.4%",
    "packSize": "35 mL Bottle",
    "schedule": "Unscheduled",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-3",
    "subcategoryFa": "بیماری‌های چشم و گوش (Eye & Ear Conditions)",
    "subcategoryEn": "Eye & Ear Conditions",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-sudafed-sinus-decongestant",
    "documentId": "doc-product-prod-sudafed-sinus-decongestant",
    "brandName": "Sudafed Sinus Decongestant",
    "genericName": "Pseudoephedrine Hydrochloride",
    "activeIngredients": "Pseudoephedrine HCl 60mg per tablet",
    "packSize": "12 Tablets",
    "schedule": "S3",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-4",
    "subcategoryFa": "دستگاه تنفس، سرماخوردگی، سرفه و آلرژی (Respiratory & Allergy)",
    "subcategoryEn": "Respiratory, Cough, Cold & Allergy",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-telfast-180",
    "documentId": "doc-product-prod-telfast-180",
    "brandName": "Telfast 180mg",
    "genericName": "Fexofenadine Hydrochloride",
    "activeIngredients": "Fexofenadine HCl 180mg tablet",
    "packSize": "30 Tablets",
    "schedule": "S2",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-4",
    "subcategoryFa": "دستگاه تنفس، سرماخوردگی، سرفه و آلرژی (Respiratory & Allergy)",
    "subcategoryEn": "Respiratory, Cough, Cold & Allergy",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-zyrtec-10",
    "documentId": "doc-product-prod-zyrtec-10",
    "brandName": "Zyrtec 10mg",
    "genericName": "Cetirizine Hydrochloride",
    "activeIngredients": "Cetirizine HCl 10mg tablet",
    "packSize": "30 Tablets",
    "schedule": "S2",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-4",
    "subcategoryFa": "دستگاه تنفس، سرماخوردگی، سرفه و آلرژی (Respiratory & Allergy)",
    "subcategoryEn": "Respiratory, Cough, Cold & Allergy",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-rhinocort-hayfever",
    "documentId": "doc-product-prod-rhinocort-hayfever",
    "brandName": "Rhinocort Hayfever 64mcg",
    "genericName": "Budesonide (Nasal)",
    "activeIngredients": "Budesonide 64mcg per dose",
    "packSize": "120 Doses Nasal Spray",
    "schedule": "S2",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-4",
    "subcategoryFa": "دستگاه تنفس، سرماخوردگی، سرفه و آلرژی (Respiratory & Allergy)",
    "subcategoryEn": "Respiratory, Cough, Cold & Allergy",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-dimetapp-nasal-spray",
    "documentId": "doc-product-prod-dimetapp-nasal-spray",
    "brandName": "Dimetapp 12 Hour Nasal Spray",
    "genericName": "Oxymetazoline Hydrochloride",
    "activeIngredients": "Oxymetazoline HCl 0.05% w/v",
    "packSize": "20 mL Spray",
    "schedule": "S2",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-4",
    "subcategoryFa": "دستگاه تنفس، سرماخوردگی، سرفه و آلرژی (Respiratory & Allergy)",
    "subcategoryEn": "Respiratory, Cough, Cold & Allergy",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-robitussin-dry-cough",
    "documentId": "doc-product-prod-robitussin-dry-cough",
    "brandName": "Robitussin Dry Cough Forte",
    "genericName": "Dextromethorphan Hydrobromide",
    "activeIngredients": "Dextromethorphan HBr 15mg/5mL",
    "packSize": "200 mL Liquid",
    "schedule": "S2",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-4",
    "subcategoryFa": "دستگاه تنفس، سرماخوردگی، سرفه و آلرژی (Respiratory & Allergy)",
    "subcategoryEn": "Respiratory, Cough, Cold & Allergy",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-bisolvon-chesty-forte",
    "documentId": "doc-product-prod-bisolvon-chesty-forte",
    "brandName": "Bisolvon Chesty Forte Liquid",
    "genericName": "Bromhexine Hydrochloride",
    "activeIngredients": "Bromhexine HCl 8mg/5mL",
    "packSize": "200 mL Liquid",
    "schedule": "S2",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-4",
    "subcategoryFa": "دستگاه تنفس، سرماخوردگی، سرفه و آلرژی (Respiratory & Allergy)",
    "subcategoryEn": "Respiratory, Cough, Cold & Allergy",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-ventolin-inhaler",
    "documentId": "doc-product-prod-ventolin-inhaler",
    "brandName": "Ventolin CFC-Free Inhaler 100mcg",
    "genericName": "Salbutamol",
    "activeIngredients": "Salbutamol sulfate 100mcg per actuation",
    "packSize": "200 Doses MDI Inhaler",
    "schedule": "S3",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-4",
    "subcategoryFa": "دستگاه تنفس، سرماخوردگی، سرفه و آلرژی (Respiratory & Allergy)",
    "subcategoryEn": "Respiratory, Cough, Cold & Allergy",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-nicorette-gum-4mg",
    "documentId": "doc-product-prod-nicorette-gum-4mg",
    "brandName": "Nicorette Gum 4mg",
    "genericName": "Nicotine Polacrilex",
    "activeIngredients": "Nicotine 4mg per piece",
    "packSize": "30 Pieces Chewing Gum",
    "schedule": "Unscheduled",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-4",
    "subcategoryFa": "دستگاه تنفس، سرماخوردگی، سرفه و آلرژی (Respiratory & Allergy)",
    "subcategoryEn": "Respiratory, Cough, Cold & Allergy",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-nexium-24hr",
    "documentId": "doc-product-prod-nexium-24hr",
    "brandName": "Nexium 24HR 20mg",
    "genericName": "Esomeprazole Magnesium",
    "activeIngredients": "Esomeprazole 20mg tablet",
    "packSize": "14 Tablets",
    "schedule": "S3",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-5",
    "subcategoryFa": "دستگاه گوارش، اسید معده، ریفلاکس، یبوست و اسهال (Gastrointestinal)",
    "subcategoryEn": "Gastrointestinal, Acid, IBS, Constipation & Diarrhea",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-gaviscon-dual-action",
    "documentId": "doc-product-prod-gaviscon-dual-action",
    "brandName": "Gaviscon Dual Action Liquid",
    "genericName": "Sodium Alginate + Sodium Bicarbonate + Calcium Carbonate",
    "activeIngredients": "Sodium alginate 500mg + Sodium bicarbonate 213mg + Calcium carbonate 325mg per 10mL",
    "packSize": "300 mL Liquid Suspension",
    "schedule": "Unscheduled",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-5",
    "subcategoryFa": "دستگاه گوارش، اسید معده، ریفلاکس، یبوست و اسهال (Gastrointestinal)",
    "subcategoryEn": "Gastrointestinal, Acid, IBS, Constipation & Diarrhea",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-gastro-stop-2mg",
    "documentId": "doc-product-prod-gastro-stop-2mg",
    "brandName": "Gastro-Stop 2mg",
    "genericName": "Loperamide Hydrochloride",
    "activeIngredients": "Loperamide HCl 2mg capsule",
    "packSize": "20 Capsules",
    "schedule": "S2",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-5",
    "subcategoryFa": "دستگاه گوارش، اسید معده، ریفلاکس، یبوست و اسهال (Gastrointestinal)",
    "subcategoryEn": "Gastrointestinal, Acid, IBS, Constipation & Diarrhea",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-hydralyte-effervescent",
    "documentId": "doc-product-prod-hydralyte-effervescent",
    "brandName": "Hydralyte Electrolyte Effervescent Tablets",
    "genericName": "Oral Rehydration Salts (ORS)",
    "activeIngredients": "Sodium chloride, Potassium chloride, Citric acid, Glucose",
    "packSize": "20 Effervescent Tablets",
    "schedule": "Unscheduled",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-5",
    "subcategoryFa": "دستگاه گوارش، اسید معده، ریفلاکس، یبوست و اسهال (Gastrointestinal)",
    "subcategoryEn": "Gastrointestinal, Acid, IBS, Constipation & Diarrhea",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-movicol-sachets",
    "documentId": "doc-product-prod-movicol-sachets",
    "brandName": "Movicol Sachets (Flavour Free)",
    "genericName": "Macrogol 3350 + Electrolytes",
    "activeIngredients": "Macrogol 3350 13.125g + Electrolytes per sachet",
    "packSize": "30 Sachets",
    "schedule": "Unscheduled",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-5",
    "subcategoryFa": "دستگاه گوارش، اسید معده، ریفلاکس، یبوست و اسهال (Gastrointestinal)",
    "subcategoryEn": "Gastrointestinal, Acid, IBS, Constipation & Diarrhea",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-dulcolax-5mg",
    "documentId": "doc-product-prod-dulcolax-5mg",
    "brandName": "Dulcolax 5mg Tablets",
    "genericName": "Bisacodyl",
    "activeIngredients": "Bisacodyl 5mg enteric-coated tablet",
    "packSize": "40 Tablets",
    "schedule": "Unscheduled",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-5",
    "subcategoryFa": "دستگاه گوارش، اسید معده، ریفلاکس، یبوست و اسهال (Gastrointestinal)",
    "subcategoryEn": "Gastrointestinal, Acid, IBS, Constipation & Diarrhea",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-buscopan-forte",
    "documentId": "doc-product-prod-buscopan-forte",
    "brandName": "Buscopan Forte 20mg",
    "genericName": "Hyoscine Butylbromide",
    "activeIngredients": "Hyoscine butylbromide 20mg tablet",
    "packSize": "10 Tablets",
    "schedule": "S2",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-5",
    "subcategoryFa": "دستگاه گوارش، اسید معده، ریفلاکس، یبوست و اسهال (Gastrointestinal)",
    "subcategoryEn": "Gastrointestinal, Acid, IBS, Constipation & Diarrhea",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-travacalm-original",
    "documentId": "doc-product-prod-travacalm-original",
    "brandName": "Travacalm Original",
    "genericName": "Dimenhydrinate + Hyoscine Hydrobromide + Caffeine",
    "activeIngredients": "Dimenhydrinate 50mg + Hyoscine HBr 0.2mg + Caffeine 20mg",
    "packSize": "10 Tablets",
    "schedule": "S2",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-5",
    "subcategoryFa": "دستگاه گوارش، اسید معده، ریفلاکس، یبوست و اسهال (Gastrointestinal)",
    "subcategoryEn": "Gastrointestinal, Acid, IBS, Constipation & Diarrhea",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-dermaid-1-cream",
    "documentId": "doc-product-prod-dermaid-1-cream",
    "brandName": "Dermaid 1% Cream",
    "genericName": "Hydrocortisone",
    "activeIngredients": "Hydrocortisone 10mg/g (1%) dissolved cream",
    "packSize": "30g Tube",
    "schedule": "S2",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-6",
    "subcategoryFa": "مراقبت‌های پوستی، درماتیت و اگزما (Dermatology & Skin Care)",
    "subcategoryEn": "Dermatology, Eczema & Skin Care",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-ego-qv-cream",
    "documentId": "doc-product-prod-ego-qv-cream",
    "brandName": "QV Cream 500g Pump",
    "genericName": "Emollient & Barrier Cream (Glycerol + Liquid Paraffin)",
    "activeIngredients": "Glycerol 10% + Light liquid paraffin 10% + Soft white paraffin 5%",
    "packSize": "500g Pump Bottle",
    "schedule": "Unscheduled",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-6",
    "subcategoryFa": "مراقبت‌های پوستی، درماتیت و اگزما (Dermatology & Skin Care)",
    "subcategoryEn": "Dermatology, Eczema & Skin Care",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-benzac-ac-5-gel",
    "documentId": "doc-product-prod-benzac-ac-5-gel",
    "brandName": "Benzac AC 5% Gel",
    "genericName": "Benzoyl Peroxide",
    "activeIngredients": "Benzoyl peroxide 50mg/g (5%) in acrylates copolymer",
    "packSize": "50g Tube",
    "schedule": "Unscheduled",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-6",
    "subcategoryFa": "مراقبت‌های پوستی، درماتیت و اگزما (Dermatology & Skin Care)",
    "subcategoryEn": "Dermatology, Eczema & Skin Care",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-zovirax-cold-sore-cream",
    "documentId": "doc-product-prod-zovirax-cold-sore-cream",
    "brandName": "Zovirax Cold Sore Cream 5%",
    "genericName": "Aciclovir",
    "activeIngredients": "Aciclovir 50mg/g (5%) with MAC-P enhancer",
    "packSize": "2g Pump",
    "schedule": "S2",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-6",
    "subcategoryFa": "مراقبت‌های پوستی، درماتیت و اگزما (Dermatology & Skin Care)",
    "subcategoryEn": "Dermatology, Eczema & Skin Care",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-sudocrem-healing-cream",
    "documentId": "doc-product-prod-sudocrem-healing-cream",
    "brandName": "Sudocrem Healing Cream",
    "genericName": "Zinc Oxide + Benzyl Benzoate",
    "activeIngredients": "Zinc oxide 15.25% + Benzyl benzoate 1.01% + Anhydrous hypoallergenic lanolin",
    "packSize": "125g Tub",
    "schedule": "Unscheduled",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-6",
    "subcategoryFa": "مراقبت‌های پوستی، درماتیت و اگزما (Dermatology & Skin Care)",
    "subcategoryEn": "Dermatology, Eczema & Skin Care",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-postinor-1",
    "documentId": "doc-product-prod-postinor-1",
    "brandName": "Postinor-1 1.5mg",
    "genericName": "Levonorgestrel",
    "activeIngredients": "Levonorgestrel 1.5mg tablet",
    "packSize": "1 Oral Tablet",
    "schedule": "S3",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-7",
    "subcategoryFa": "سلامت زنان و مردان، پیشگیری اضطراری و UTI (Women & Men Health)",
    "subcategoryEn": "Women's & Men's Health & Emergency Contraception",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-ellaone-30mg",
    "documentId": "doc-product-prod-ellaone-30mg",
    "brandName": "EllaOne 30mg",
    "genericName": "Ulipristal Acetate",
    "activeIngredients": "Ulipristal acetate 30mg tablet",
    "packSize": "1 Oral Tablet",
    "schedule": "S3",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-7",
    "subcategoryFa": "سلامت زنان و مردان، پیشگیری اضطراری و UTI (Women & Men Health)",
    "subcategoryEn": "Women's & Men's Health & Emergency Contraception",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-ural-sachets",
    "documentId": "doc-product-prod-ural-sachets",
    "brandName": "Ural Effervescent Granules",
    "genericName": "Urinary Alkaliniser (Sodium Bicarbonate + Tartaric Acid + Citric Acid)",
    "activeIngredients": "Sodium bicarbonate 1.76g + Tartaric acid 890mg + Citric acid 720mg + Sodium citrate 630mg per sachet",
    "packSize": "28 Sachets",
    "schedule": "Unscheduled",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-7",
    "subcategoryFa": "سلامت زنان و مردان، پیشگیری اضطراری و UTI (Women & Men Health)",
    "subcategoryEn": "Women's & Men's Health & Emergency Contraception",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-canesten-vaginal-pessary",
    "documentId": "doc-product-prod-canesten-vaginal-pessary",
    "brandName": "Canesten 1-Day Pessary 500mg",
    "genericName": "Clotrimazole (Vaginal)",
    "activeIngredients": "Clotrimazole 500mg vaginal pessary + 10g cream",
    "packSize": "1 Pessary with Applicator + 10g Soothing Cream",
    "schedule": "S3",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-7",
    "subcategoryFa": "سلامت زنان و مردان، پیشگیری اضطراری و UTI (Women & Men Health)",
    "subcategoryEn": "Women's & Men's Health & Emergency Contraception",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-bonjela-teething-gel",
    "documentId": "doc-product-prod-bonjela-teething-gel",
    "brandName": "Bonjela Teething Gel",
    "genericName": "Choline Salicylate + Cetalkonium Chloride",
    "activeIngredients": "Choline salicylate 8.7% + Cetalkonium chloride 0.01%",
    "packSize": "15g Tube",
    "schedule": "S2",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-7",
    "subcategoryFa": "سلامت زنان و مردان، پیشگیری اضطراری و UTI (Women & Men Health)",
    "subcategoryEn": "Women's & Men's Health & Emergency Contraception",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-pritor-80mg",
    "documentId": "doc-product-prod-pritor-80mg",
    "brandName": "Pritor 80mg",
    "genericName": "Telmisartan",
    "activeIngredients": "Telmisartan 80mg tablet",
    "packSize": "28 Tablets",
    "schedule": "S4",
    "categoryId": "cat-2",
    "categoryFa": "دارودرمانی قلب، عروق و کلیه (Cardiovascular & Renal)",
    "categoryEn": "Cardiovascular & Renal Pharmacology",
    "subcategoryId": "sub-2-1",
    "subcategoryFa": "پرفشاری خون و سیستم رنین-آنژیوتانسین (Hypertension & RAAS)",
    "subcategoryEn": "Hypertension & Renin-Angiotensin System",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-coversyl-5mg",
    "documentId": "doc-product-prod-coversyl-5mg",
    "brandName": "Coversyl 5mg",
    "genericName": "Perindopril Arginine",
    "activeIngredients": "Perindopril arginine 5mg tablet",
    "packSize": "30 Tablets",
    "schedule": "S4",
    "categoryId": "cat-2",
    "categoryFa": "دارودرمانی قلب، عروق و کلیه (Cardiovascular & Renal)",
    "categoryEn": "Cardiovascular & Renal Pharmacology",
    "subcategoryId": "sub-2-1",
    "subcategoryFa": "پرفشاری خون و سیستم رنین-آنژیوتانسین (Hypertension & RAAS)",
    "subcategoryEn": "Hypertension & Renin-Angiotensin System",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-atacand-16mg",
    "documentId": "doc-product-prod-atacand-16mg",
    "brandName": "Atacand 16mg",
    "genericName": "Candesartan Cilexetil",
    "activeIngredients": "Candesartan cilexetil 16mg tablet",
    "packSize": "30 Tablets",
    "schedule": "S4",
    "categoryId": "cat-2",
    "categoryFa": "دارودرمانی قلب، عروق و کلیه (Cardiovascular & Renal)",
    "categoryEn": "Cardiovascular & Renal Pharmacology",
    "subcategoryId": "sub-2-1",
    "subcategoryFa": "پرفشاری خون و سیستم رنین-آنژیوتانسین (Hypertension & RAAS)",
    "subcategoryEn": "Hypertension & Renin-Angiotensin System",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-norvasc-5mg",
    "documentId": "doc-product-prod-norvasc-5mg",
    "brandName": "Norvasc 5mg",
    "genericName": "Amlodipine Besylate",
    "activeIngredients": "Amlodipine besylate 5mg tablet",
    "packSize": "30 Tablets",
    "schedule": "S4",
    "categoryId": "cat-2",
    "categoryFa": "دارودرمانی قلب، عروق و کلیه (Cardiovascular & Renal)",
    "categoryEn": "Cardiovascular & Renal Pharmacology",
    "subcategoryId": "sub-2-1",
    "subcategoryFa": "پرفشاری خون و سیستم رنین-آنژیوتانسین (Hypertension & RAAS)",
    "subcategoryEn": "Hypertension & Renin-Angiotensin System",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-dithiazide-25mg",
    "documentId": "doc-product-prod-dithiazide-25mg",
    "brandName": "Dithiazide 25mg",
    "genericName": "Hydrochlorothiazide",
    "activeIngredients": "Hydrochlorothiazide 25mg tablet",
    "packSize": "100 Tablets",
    "schedule": "S4",
    "categoryId": "cat-2",
    "categoryFa": "دارودرمانی قلب، عروق و کلیه (Cardiovascular & Renal)",
    "categoryEn": "Cardiovascular & Renal Pharmacology",
    "subcategoryId": "sub-2-1",
    "subcategoryFa": "پرفشاری خون و سیستم رنین-آنژیوتانسین (Hypertension & RAAS)",
    "subcategoryEn": "Hypertension & Renin-Angiotensin System",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-trandate-100mg",
    "documentId": "doc-product-prod-trandate-100mg",
    "brandName": "Trandate 100mg",
    "genericName": "Labetalol Hydrochloride",
    "activeIngredients": "Labetalol HCl 100mg tablet",
    "packSize": "100 Tablets",
    "schedule": "S4",
    "categoryId": "cat-2",
    "categoryFa": "دارودرمانی قلب، عروق و کلیه (Cardiovascular & Renal)",
    "categoryEn": "Cardiovascular & Renal Pharmacology",
    "subcategoryId": "sub-2-1",
    "subcategoryFa": "پرفشاری خون و سیستم رنین-آنژیوتانسین (Hypertension & RAAS)",
    "subcategoryEn": "Hypertension & Renin-Angiotensin System",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-coumadin-3mg",
    "documentId": "doc-product-prod-coumadin-3mg",
    "brandName": "Coumadin 3mg",
    "genericName": "Warfarin Sodium",
    "activeIngredients": "Warfarin Sodium 3mg tablet",
    "packSize": "50 Tablets",
    "schedule": "S4",
    "categoryId": "cat-2",
    "categoryFa": "دارودرمانی قلب، عروق و کلیه (Cardiovascular & Renal)",
    "categoryEn": "Cardiovascular & Renal Pharmacology",
    "subcategoryId": "sub-2-2",
    "subcategoryFa": "ضدانعقادها، ضدپلاکت‌ها و ترومبوز (Anticoagulants & Antiplatelets)",
    "subcategoryEn": "Anticoagulants, Antiplatelets & Thrombosis",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-xarelto-20mg",
    "documentId": "doc-product-prod-xarelto-20mg",
    "brandName": "Xarelto 20mg",
    "genericName": "Rivaroxaban",
    "activeIngredients": "Rivaroxaban 20mg tablet",
    "packSize": "28 Tablets",
    "schedule": "S4",
    "categoryId": "cat-2",
    "categoryFa": "دارودرمانی قلب، عروق و کلیه (Cardiovascular & Renal)",
    "categoryEn": "Cardiovascular & Renal Pharmacology",
    "subcategoryId": "sub-2-2",
    "subcategoryFa": "ضدانعقادها، ضدپلاکت‌ها و ترومبوز (Anticoagulants & Antiplatelets)",
    "subcategoryEn": "Anticoagulants, Antiplatelets & Thrombosis",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-eliquis-5mg",
    "documentId": "doc-product-prod-eliquis-5mg",
    "brandName": "Eliquis 5mg",
    "genericName": "Apixaban",
    "activeIngredients": "Apixaban 5mg tablet",
    "packSize": "60 Tablets",
    "schedule": "S4",
    "categoryId": "cat-2",
    "categoryFa": "دارودرمانی قلب، عروق و کلیه (Cardiovascular & Renal)",
    "categoryEn": "Cardiovascular & Renal Pharmacology",
    "subcategoryId": "sub-2-2",
    "subcategoryFa": "ضدانعقادها، ضدپلاکت‌ها و ترومبوز (Anticoagulants & Antiplatelets)",
    "subcategoryEn": "Anticoagulants, Antiplatelets & Thrombosis",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-plavix-75mg",
    "documentId": "doc-product-prod-plavix-75mg",
    "brandName": "Plavix 75mg",
    "genericName": "Clopidogrel Hydrogen Sulfate",
    "activeIngredients": "Clopidogrel 75mg tablet",
    "packSize": "28 Tablets",
    "schedule": "S4",
    "categoryId": "cat-2",
    "categoryFa": "دارودرمانی قلب، عروق و کلیه (Cardiovascular & Renal)",
    "categoryEn": "Cardiovascular & Renal Pharmacology",
    "subcategoryId": "sub-2-2",
    "subcategoryFa": "ضدانعقادها، ضدپلاکت‌ها و ترومبوز (Anticoagulants & Antiplatelets)",
    "subcategoryEn": "Anticoagulants, Antiplatelets & Thrombosis",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-cartia-100mg",
    "documentId": "doc-product-prod-cartia-100mg",
    "brandName": "Cartia 100mg Duentric",
    "genericName": "Aspirin (Low Dose Antiplatelet)",
    "activeIngredients": "Aspirin 100mg enteric coated tablet",
    "packSize": "84 Tablets",
    "schedule": "Unscheduled",
    "categoryId": "cat-2",
    "categoryFa": "دارودرمانی قلب، عروق و کلیه (Cardiovascular & Renal)",
    "categoryEn": "Cardiovascular & Renal Pharmacology",
    "subcategoryId": "sub-2-2",
    "subcategoryFa": "ضدانعقادها، ضدپلاکت‌ها و ترومبوز (Anticoagulants & Antiplatelets)",
    "subcategoryEn": "Anticoagulants, Antiplatelets & Thrombosis",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-lanoxin-pg-62-5mcg",
    "documentId": "doc-product-prod-lanoxin-pg-62-5mcg",
    "brandName": "Lanoxin-PG 62.5mcg",
    "genericName": "Digoxin",
    "activeIngredients": "Digoxin 62.5 micrograms tablet",
    "packSize": "200 Tablets",
    "schedule": "S4",
    "categoryId": "cat-2",
    "categoryFa": "دارودرمانی قلب، عروق و کلیه (Cardiovascular & Renal)",
    "categoryEn": "Cardiovascular & Renal Pharmacology",
    "subcategoryId": "sub-2-3",
    "subcategoryFa": "نارسایی قلبی و داروهای ضدآریتمی (Heart Failure & Antiarrhythmics)",
    "subcategoryEn": "Heart Failure & Antiarrhythmics",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-concor-5mg",
    "documentId": "doc-product-prod-concor-5mg",
    "brandName": "Concor 5mg",
    "genericName": "Bisoprolol Fumarate",
    "activeIngredients": "Bisoprolol fumarate 5mg tablet",
    "packSize": "28 Tablets",
    "schedule": "S4",
    "categoryId": "cat-2",
    "categoryFa": "دارودرمانی قلب، عروق و کلیه (Cardiovascular & Renal)",
    "categoryEn": "Cardiovascular & Renal Pharmacology",
    "subcategoryId": "sub-2-3",
    "subcategoryFa": "نارسایی قلبی و داروهای ضدآریتمی (Heart Failure & Antiarrhythmics)",
    "subcategoryEn": "Heart Failure & Antiarrhythmics",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-aldactone-25mg",
    "documentId": "doc-product-prod-aldactone-25mg",
    "brandName": "Aldactone 25mg",
    "genericName": "Spironolactone",
    "activeIngredients": "Spironolactone 25mg tablet",
    "packSize": "100 Tablets",
    "schedule": "S4",
    "categoryId": "cat-2",
    "categoryFa": "دارودرمانی قلب، عروق و کلیه (Cardiovascular & Renal)",
    "categoryEn": "Cardiovascular & Renal Pharmacology",
    "subcategoryId": "sub-2-3",
    "subcategoryFa": "نارسایی قلبی و داروهای ضدآریتمی (Heart Failure & Antiarrhythmics)",
    "subcategoryEn": "Heart Failure & Antiarrhythmics",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-cordarone-x-200mg",
    "documentId": "doc-product-prod-cordarone-x-200mg",
    "brandName": "Cordarone X 200mg",
    "genericName": "Amiodarone Hydrochloride",
    "activeIngredients": "Amiodarone HCl 200mg tablet",
    "packSize": "30 Tablets",
    "schedule": "S4",
    "categoryId": "cat-2",
    "categoryFa": "دارودرمانی قلب، عروق و کلیه (Cardiovascular & Renal)",
    "categoryEn": "Cardiovascular & Renal Pharmacology",
    "subcategoryId": "sub-2-3",
    "subcategoryFa": "نارسایی قلبی و داروهای ضدآریتمی (Heart Failure & Antiarrhythmics)",
    "subcategoryEn": "Heart Failure & Antiarrhythmics",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-nitrolingual-spray",
    "documentId": "doc-product-prod-nitrolingual-spray",
    "brandName": "Nitrolingual Pumpspray 400mcg",
    "genericName": "Glyceryl Trinitrate (GTN)",
    "activeIngredients": "Glyceryl trinitrate 400 micrograms per metered spray",
    "packSize": "200 Doses Sublingual Spray",
    "schedule": "S3",
    "categoryId": "cat-2",
    "categoryFa": "دارودرمانی قلب، عروق و کلیه (Cardiovascular & Renal)",
    "categoryEn": "Cardiovascular & Renal Pharmacology",
    "subcategoryId": "sub-2-3",
    "subcategoryFa": "نارسایی قلبی و داروهای ضدآریتمی (Heart Failure & Antiarrhythmics)",
    "subcategoryEn": "Heart Failure & Antiarrhythmics",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-forxiga-10mg",
    "documentId": "doc-product-prod-forxiga-10mg",
    "brandName": "Forxiga 10mg",
    "genericName": "Dapagliflozin",
    "activeIngredients": "Dapagliflozin 10mg tablet",
    "packSize": "28 Tablets",
    "schedule": "S4",
    "categoryId": "cat-2",
    "categoryFa": "دارودرمانی قلب، عروق و کلیه (Cardiovascular & Renal)",
    "categoryEn": "Cardiovascular & Renal Pharmacology",
    "subcategoryId": "sub-2-3",
    "subcategoryFa": "نارسایی قلبی و داروهای ضدآریتمی (Heart Failure & Antiarrhythmics)",
    "subcategoryEn": "Heart Failure & Antiarrhythmics",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-lipitor-20mg",
    "documentId": "doc-product-prod-lipitor-20mg",
    "brandName": "Lipitor 20mg",
    "genericName": "Atorvastatin Calcium",
    "activeIngredients": "Atorvastatin 20mg tablet",
    "packSize": "30 Tablets",
    "schedule": "S4",
    "categoryId": "cat-2",
    "categoryFa": "دارودرمانی قلب، عروق و کلیه (Cardiovascular & Renal)",
    "categoryEn": "Cardiovascular & Renal Pharmacology",
    "subcategoryId": "sub-2-4",
    "subcategoryFa": "کاهنده چربی خون و استاتین‌ها (Lipid-Lowering & Statins)",
    "subcategoryEn": "Lipid-Lowering & Statins",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-crestor-10mg",
    "documentId": "doc-product-prod-crestor-10mg",
    "brandName": "Crestor 10mg",
    "genericName": "Rosuvastatin Calcium",
    "activeIngredients": "Rosuvastatin calcium 10mg tablet",
    "packSize": "30 Tablets",
    "schedule": "S4",
    "categoryId": "cat-2",
    "categoryFa": "دارودرمانی قلب، عروق و کلیه (Cardiovascular & Renal)",
    "categoryEn": "Cardiovascular & Renal Pharmacology",
    "subcategoryId": "sub-2-4",
    "subcategoryFa": "کاهنده چربی خون و استاتین‌ها (Lipid-Lowering & Statins)",
    "subcategoryEn": "Lipid-Lowering & Statins",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-ezetrol-10mg",
    "documentId": "doc-product-prod-ezetrol-10mg",
    "brandName": "Ezetrol 10mg",
    "genericName": "Ezetimibe",
    "activeIngredients": "Ezetimibe 10mg tablet",
    "packSize": "30 Tablets",
    "schedule": "S4",
    "categoryId": "cat-2",
    "categoryFa": "دارودرمانی قلب، عروق و کلیه (Cardiovascular & Renal)",
    "categoryEn": "Cardiovascular & Renal Pharmacology",
    "subcategoryId": "sub-2-4",
    "subcategoryFa": "کاهنده چربی خون و استاتین‌ها (Lipid-Lowering & Statins)",
    "subcategoryEn": "Lipid-Lowering & Statins",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-lipirex-145mg",
    "documentId": "doc-product-prod-lipirex-145mg",
    "brandName": "Lipirex 145mg",
    "genericName": "Fenofibrate (Nanoparticle)",
    "activeIngredients": "Fenofibrate 145mg nanoparticle tablet",
    "packSize": "30 Tablets",
    "schedule": "S4",
    "categoryId": "cat-2",
    "categoryFa": "دارودرمانی قلب، عروق و کلیه (Cardiovascular & Renal)",
    "categoryEn": "Cardiovascular & Renal Pharmacology",
    "subcategoryId": "sub-2-4",
    "subcategoryFa": "کاهنده چربی خون و استاتین‌ها (Lipid-Lowering & Statins)",
    "subcategoryEn": "Lipid-Lowering & Statins",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-zocor-20mg",
    "documentId": "doc-product-prod-zocor-20mg",
    "brandName": "Zocor 20mg",
    "genericName": "Simvastatin",
    "activeIngredients": "Simvastatin 20mg tablet",
    "packSize": "30 Tablets",
    "schedule": "S4",
    "categoryId": "cat-2",
    "categoryFa": "دارودرمانی قلب، عروق و کلیه (Cardiovascular & Renal)",
    "categoryEn": "Cardiovascular & Renal Pharmacology",
    "subcategoryId": "sub-2-4",
    "subcategoryFa": "کاهنده چربی خون و استاتین‌ها (Lipid-Lowering & Statins)",
    "subcategoryEn": "Lipid-Lowering & Statins",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-lexapro-10mg",
    "documentId": "doc-product-prod-lexapro-10mg",
    "brandName": "Lexapro 10mg",
    "genericName": "Escitalopram",
    "activeIngredients": "Escitalopram Oxalate 10mg tablet",
    "packSize": "28 Tablets",
    "schedule": "S4",
    "categoryId": "cat-3",
    "categoryFa": "سیستم عصبی مرکزی و روانپزشکی (CNS & Mental Health)",
    "categoryEn": "Central Nervous System & Mental Health",
    "subcategoryId": "sub-3-1",
    "subcategoryFa": "ضدافسردگی‌ها و اختلالات خلقی (Antidepressants & Mood)",
    "subcategoryEn": "Antidepressants, SSRIs, SNRIs & Mood",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-efexor-xr-75mg",
    "documentId": "doc-product-prod-efexor-xr-75mg",
    "brandName": "Efexor-XR 75mg",
    "genericName": "Venlafaxine Hydrochloride",
    "activeIngredients": "Venlafaxine HCl 75mg extended-release capsule",
    "packSize": "28 Extended-Release Capsules",
    "schedule": "S4",
    "categoryId": "cat-3",
    "categoryFa": "سیستم عصبی مرکزی و روانپزشکی (CNS & Mental Health)",
    "categoryEn": "Central Nervous System & Mental Health",
    "subcategoryId": "sub-3-1",
    "subcategoryFa": "ضدافسردگی‌ها و اختلالات خلقی (Antidepressants & Mood)",
    "subcategoryEn": "Antidepressants, SSRIs, SNRIs & Mood",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-endep-25mg",
    "documentId": "doc-product-prod-endep-25mg",
    "brandName": "Endep 25mg",
    "genericName": "Amitriptyline Hydrochloride",
    "activeIngredients": "Amitriptyline HCl 25mg tablet",
    "packSize": "50 Tablets",
    "schedule": "S4",
    "categoryId": "cat-3",
    "categoryFa": "سیستم عصبی مرکزی و روانپزشکی (CNS & Mental Health)",
    "categoryEn": "Central Nervous System & Mental Health",
    "subcategoryId": "sub-3-1",
    "subcategoryFa": "ضدافسردگی‌ها و اختلالات خلقی (Antidepressants & Mood)",
    "subcategoryEn": "Antidepressants, SSRIs, SNRIs & Mood",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-avanza-30mg",
    "documentId": "doc-product-prod-avanza-30mg",
    "brandName": "Avanza 30mg (SolTab / Film-Coated)",
    "genericName": "Mirtazapine",
    "activeIngredients": "Mirtazapine 30mg tablet",
    "packSize": "30 Tablets",
    "schedule": "S4",
    "categoryId": "cat-3",
    "categoryFa": "سیستم عصبی مرکزی و روانپزشکی (CNS & Mental Health)",
    "categoryEn": "Central Nervous System & Mental Health",
    "subcategoryId": "sub-3-1",
    "subcategoryFa": "ضدافسردگی‌ها و اختلالات خلقی (Antidepressants & Mood)",
    "subcategoryEn": "Antidepressants, SSRIs, SNRIs & Mood",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-prozac-20mg",
    "documentId": "doc-product-prod-prozac-20mg",
    "brandName": "Prozac 20mg",
    "genericName": "Fluoxetine Hydrochloride",
    "activeIngredients": "Fluoxetine HCl 20mg capsule",
    "packSize": "28 Capsules",
    "schedule": "S4",
    "categoryId": "cat-3",
    "categoryFa": "سیستم عصبی مرکزی و روانپزشکی (CNS & Mental Health)",
    "categoryEn": "Central Nervous System & Mental Health",
    "subcategoryId": "sub-3-1",
    "subcategoryFa": "ضدافسردگی‌ها و اختلالات خلقی (Antidepressants & Mood)",
    "subcategoryEn": "Antidepressants, SSRIs, SNRIs & Mood",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-lithicarb-250mg",
    "documentId": "doc-product-prod-lithicarb-250mg",
    "brandName": "Lithicarb 250mg",
    "genericName": "Lithium Carbonate",
    "activeIngredients": "Lithium Carbonate 250mg tablet",
    "packSize": "100 Tablets",
    "schedule": "S4",
    "categoryId": "cat-3",
    "categoryFa": "سیستم عصبی مرکزی و روانپزشکی (CNS & Mental Health)",
    "categoryEn": "Central Nervous System & Mental Health",
    "subcategoryId": "sub-3-1",
    "subcategoryFa": "ضدافسردگی‌ها و اختلالات خلقی (Antidepressants & Mood)",
    "subcategoryEn": "Antidepressants, SSRIs, SNRIs & Mood",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-epilim-500mg",
    "documentId": "doc-product-prod-epilim-500mg",
    "brandName": "Epilim 500mg EC",
    "genericName": "Sodium Valproate",
    "activeIngredients": "Sodium Valproate 500mg enteric coated tablet",
    "packSize": "100 Tablets",
    "schedule": "S4",
    "categoryId": "cat-3",
    "categoryFa": "سیستم عصبی مرکزی و روانپزشکی (CNS & Mental Health)",
    "categoryEn": "Central Nervous System & Mental Health",
    "subcategoryId": "sub-3-2",
    "subcategoryFa": "داروهای ضدتشنج و دردهای نوروپاتیک (Antiepileptics & Neuropathic Pain)",
    "subcategoryEn": "Antiepileptics & Neuropathic Pain",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-lyrica-75mg",
    "documentId": "doc-product-prod-lyrica-75mg",
    "brandName": "Lyrica 75mg",
    "genericName": "Pregabalin",
    "activeIngredients": "Pregabalin 75mg capsule",
    "packSize": "56 Capsules",
    "schedule": "S4",
    "categoryId": "cat-3",
    "categoryFa": "سیستم عصبی مرکزی و روانپزشکی (CNS & Mental Health)",
    "categoryEn": "Central Nervous System & Mental Health",
    "subcategoryId": "sub-3-2",
    "subcategoryFa": "داروهای ضدتشنج و دردهای نوروپاتیک (Antiepileptics & Neuropathic Pain)",
    "subcategoryEn": "Antiepileptics & Neuropathic Pain",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-tegretol-200mg",
    "documentId": "doc-product-prod-tegretol-200mg",
    "brandName": "Tegretol 200mg",
    "genericName": "Carbamazepine",
    "activeIngredients": "Carbamazepine 200mg tablet",
    "packSize": "200 Tablets",
    "schedule": "S4",
    "categoryId": "cat-3",
    "categoryFa": "سیستم عصبی مرکزی و روانپزشکی (CNS & Mental Health)",
    "categoryEn": "Central Nervous System & Mental Health",
    "subcategoryId": "sub-3-2",
    "subcategoryFa": "داروهای ضدتشنج و دردهای نوروپاتیک (Antiepileptics & Neuropathic Pain)",
    "subcategoryEn": "Antiepileptics & Neuropathic Pain",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-lamictal-50mg",
    "documentId": "doc-product-prod-lamictal-50mg",
    "brandName": "Lamictal 50mg",
    "genericName": "Lamotrigine",
    "activeIngredients": "Lamotrigine 50mg dispersible/chewable tablet",
    "packSize": "56 Dispersible Tablets",
    "schedule": "S4",
    "categoryId": "cat-3",
    "categoryFa": "سیستم عصبی مرکزی و روانپزشکی (CNS & Mental Health)",
    "categoryEn": "Central Nervous System & Mental Health",
    "subcategoryId": "sub-3-2",
    "subcategoryFa": "داروهای ضدتشنج و دردهای نوروپاتیک (Antiepileptics & Neuropathic Pain)",
    "subcategoryEn": "Antiepileptics & Neuropathic Pain",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-keppra-500mg",
    "documentId": "doc-product-prod-keppra-500mg",
    "brandName": "Keppra 500mg",
    "genericName": "Levetiracetam",
    "activeIngredients": "Levetiracetam 500mg film-coated tablet",
    "packSize": "60 Tablets",
    "schedule": "S4",
    "categoryId": "cat-3",
    "categoryFa": "سیستم عصبی مرکزی و روانپزشکی (CNS & Mental Health)",
    "categoryEn": "Central Nervous System & Mental Health",
    "subcategoryId": "sub-3-2",
    "subcategoryFa": "داروهای ضدتشنج و دردهای نوروپاتیک (Antiepileptics & Neuropathic Pain)",
    "subcategoryEn": "Antiepileptics & Neuropathic Pain",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-valium-5mg",
    "documentId": "doc-product-prod-valium-5mg",
    "brandName": "Valium 5mg",
    "genericName": "Diazepam",
    "activeIngredients": "Diazepam 5mg tablet",
    "packSize": "50 Tablets",
    "schedule": "S4",
    "categoryId": "cat-3",
    "categoryFa": "سیستم عصبی مرکزی و روانپزشکی (CNS & Mental Health)",
    "categoryEn": "Central Nervous System & Mental Health",
    "subcategoryId": "sub-3-3",
    "subcategoryFa": "آرام‌بخش‌ها، خواب‌آورها و بنزودیازپین‌ها (Sedatives & Hypnotics)",
    "subcategoryEn": "Sedatives, Hypnotics & Anxiolytics",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-stilnox-10mg",
    "documentId": "doc-product-prod-stilnox-10mg",
    "brandName": "Stilnox 10mg",
    "genericName": "Zolpidem Tartrate",
    "activeIngredients": "Zolpidem Tartrate 10mg tablet",
    "packSize": "14 Tablets",
    "schedule": "S4",
    "categoryId": "cat-3",
    "categoryFa": "سیستم عصبی مرکزی و روانپزشکی (CNS & Mental Health)",
    "categoryEn": "Central Nervous System & Mental Health",
    "subcategoryId": "sub-3-3",
    "subcategoryFa": "آرام‌بخش‌ها، خواب‌آورها و بنزودیازپین‌ها (Sedatives & Hypnotics)",
    "subcategoryEn": "Sedatives, Hypnotics & Anxiolytics",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-temaze-10mg",
    "documentId": "doc-product-prod-temaze-10mg",
    "brandName": "Temaze 10mg",
    "genericName": "Temazepam",
    "activeIngredients": "Temazepam 10mg tablet",
    "packSize": "25 Tablets",
    "schedule": "S4",
    "categoryId": "cat-3",
    "categoryFa": "سیستم عصبی مرکزی و روانپزشکی (CNS & Mental Health)",
    "categoryEn": "Central Nervous System & Mental Health",
    "subcategoryId": "sub-3-3",
    "subcategoryFa": "آرام‌بخش‌ها، خواب‌آورها و بنزودیازپین‌ها (Sedatives & Hypnotics)",
    "subcategoryEn": "Sedatives, Hypnotics & Anxiolytics",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-circadin-2mg",
    "documentId": "doc-product-prod-circadin-2mg",
    "brandName": "Circadin 2mg PR",
    "genericName": "Melatonin (Prolonged Release)",
    "activeIngredients": "Melatonin 2mg prolonged-release tablet",
    "packSize": "30 Prolonged-Release Tablets",
    "schedule": "S4",
    "categoryId": "cat-3",
    "categoryFa": "سیستم عصبی مرکزی و روانپزشکی (CNS & Mental Health)",
    "categoryEn": "Central Nervous System & Mental Health",
    "subcategoryId": "sub-3-3",
    "subcategoryFa": "آرام‌بخش‌ها، خواب‌آورها و بنزودیازپین‌ها (Sedatives & Hypnotics)",
    "subcategoryEn": "Sedatives, Hypnotics & Anxiolytics",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-nyxoid-nasal-spray",
    "documentId": "doc-product-prod-nyxoid-nasal-spray",
    "brandName": "Nyxoid Nasal Spray 1.8mg",
    "genericName": "Naloxone Hydrochloride",
    "activeIngredients": "Naloxone HCl 1.8mg single-dose nasal spray",
    "packSize": "2 Single-Dose Dispensers",
    "schedule": "S3",
    "categoryId": "cat-3",
    "categoryFa": "سیستم عصبی مرکزی و روانپزشکی (CNS & Mental Health)",
    "categoryEn": "Central Nervous System & Mental Health",
    "subcategoryId": "sub-3-4",
    "subcategoryFa": "مسکن‌های اپیوئیدی و مدیریت درد (Opioid Analgesia & Pain)",
    "subcategoryEn": "Opioid Analgesia & Pain Management",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-durogesic-25mcg",
    "documentId": "doc-product-prod-durogesic-25mcg",
    "brandName": "Durogesic 25mcg/hr Patch",
    "genericName": "Fentanyl (Transdermal)",
    "activeIngredients": "Fentanyl 4.2mg transdermal patch (releases 25 micrograms/hour over 72 hours)",
    "packSize": "5 Transdermal Patches",
    "schedule": "S8",
    "categoryId": "cat-3",
    "categoryFa": "سیستم عصبی مرکزی و روانپزشکی (CNS & Mental Health)",
    "categoryEn": "Central Nervous System & Mental Health",
    "subcategoryId": "sub-3-4",
    "subcategoryFa": "مسکن‌های اپیوئیدی و مدیریت درد (Opioid Analgesia & Pain)",
    "subcategoryEn": "Opioid Analgesia & Pain Management",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-targin-10-5mg",
    "documentId": "doc-product-prod-targin-10-5mg",
    "brandName": "Targin 10mg/5mg PR",
    "genericName": "Oxycodone Hydrochloride + Naloxone Hydrochloride",
    "activeIngredients": "Oxycodone HCl 10mg + Naloxone HCl 5mg prolonged-release tablet",
    "packSize": "28 Prolonged-Release Tablets",
    "schedule": "S8",
    "categoryId": "cat-3",
    "categoryFa": "سیستم عصبی مرکزی و روانپزشکی (CNS & Mental Health)",
    "categoryEn": "Central Nervous System & Mental Health",
    "subcategoryId": "sub-3-4",
    "subcategoryFa": "مسکن‌های اپیوئیدی و مدیریت درد (Opioid Analgesia & Pain)",
    "subcategoryEn": "Opioid Analgesia & Pain Management",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-endone-5mg",
    "documentId": "doc-product-prod-endone-5mg",
    "brandName": "Endone 5mg",
    "genericName": "Oxycodone Hydrochloride (Immediate Release)",
    "activeIngredients": "Oxycodone HCl 5mg tablet",
    "packSize": "20 Tablets",
    "schedule": "S8",
    "categoryId": "cat-3",
    "categoryFa": "سیستم عصبی مرکزی و روانپزشکی (CNS & Mental Health)",
    "categoryEn": "Central Nervous System & Mental Health",
    "subcategoryId": "sub-3-4",
    "subcategoryFa": "مسکن‌های اپیوئیدی و مدیریت درد (Opioid Analgesia & Pain)",
    "subcategoryEn": "Opioid Analgesia & Pain Management",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-tramal-50mg",
    "documentId": "doc-product-prod-tramal-50mg",
    "brandName": "Tramal 50mg",
    "genericName": "Tramadol Hydrochloride",
    "activeIngredients": "Tramadol HCl 50mg capsule",
    "packSize": "20 Capsules",
    "schedule": "S4",
    "categoryId": "cat-3",
    "categoryFa": "سیستم عصبی مرکزی و روانپزشکی (CNS & Mental Health)",
    "categoryEn": "Central Nervous System & Mental Health",
    "subcategoryId": "sub-3-4",
    "subcategoryFa": "مسکن‌های اپیوئیدی و مدیریت درد (Opioid Analgesia & Pain)",
    "subcategoryEn": "Opioid Analgesia & Pain Management",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-diabex-500mg",
    "documentId": "doc-product-prod-diabex-500mg",
    "brandName": "Diabex 500mg",
    "genericName": "Metformin Hydrochloride",
    "activeIngredients": "Metformin HCl 500mg tablet",
    "packSize": "100 Tablets",
    "schedule": "S4",
    "categoryId": "cat-4",
    "categoryFa": "بیماری‌های غدد، متابولیسم و استخوان (Endocrine & Metabolic)",
    "categoryEn": "Endocrine, Bone & Metabolic Diseases",
    "subcategoryId": "sub-4-1",
    "subcategoryFa": "دیابت ملیتوس، انسولین و داروهای قند خون (Diabetes Mellitus)",
    "subcategoryEn": "Diabetes Mellitus, Insulin, SGLT2i & GLP-1",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-jardiance-10mg",
    "documentId": "doc-product-prod-jardiance-10mg",
    "brandName": "Jardiance 10mg",
    "genericName": "Empagliflozin",
    "activeIngredients": "Empagliflozin 10mg film-coated tablet",
    "packSize": "30 Tablets",
    "schedule": "S4",
    "categoryId": "cat-4",
    "categoryFa": "بیماری‌های غدد، متابولیسم و استخوان (Endocrine & Metabolic)",
    "categoryEn": "Endocrine, Bone & Metabolic Diseases",
    "subcategoryId": "sub-4-1",
    "subcategoryFa": "دیابت ملیتوس، انسولین و داروهای قند خون (Diabetes Mellitus)",
    "subcategoryEn": "Diabetes Mellitus, Insulin, SGLT2i & GLP-1",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-ozempic-0-5mg",
    "documentId": "doc-product-prod-ozempic-0-5mg",
    "brandName": "Ozempic 0.5mg Pen",
    "genericName": "Semaglutide",
    "activeIngredients": "Semaglutide 1.34 mg/mL pre-filled pen (delivers 0.25mg or 0.5mg weekly doses)",
    "packSize": "1 Pre-filled Pen + 6 NovoFine Plus Needles",
    "schedule": "S4",
    "categoryId": "cat-4",
    "categoryFa": "بیماری‌های غدد، متابولیسم و استخوان (Endocrine & Metabolic)",
    "categoryEn": "Endocrine, Bone & Metabolic Diseases",
    "subcategoryId": "sub-4-1",
    "subcategoryFa": "دیابت ملیتوس، انسولین و داروهای قند خون (Diabetes Mellitus)",
    "subcategoryEn": "Diabetes Mellitus, Insulin, SGLT2i & GLP-1",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-diamicron-60mg-mr",
    "documentId": "doc-product-prod-diamicron-60mg-mr",
    "brandName": "Diamicron 60mg MR",
    "genericName": "Gliclazide",
    "activeIngredients": "Gliclazide 60mg modified-release tablet",
    "packSize": "60 Modified-Release Tablets",
    "schedule": "S4",
    "categoryId": "cat-4",
    "categoryFa": "بیماری‌های غدد، متابولیسم و استخوان (Endocrine & Metabolic)",
    "categoryEn": "Endocrine, Bone & Metabolic Diseases",
    "subcategoryId": "sub-4-1",
    "subcategoryFa": "دیابت ملیتوس، انسولین و داروهای قند خون (Diabetes Mellitus)",
    "subcategoryEn": "Diabetes Mellitus, Insulin, SGLT2i & GLP-1",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-lantus-solostar",
    "documentId": "doc-product-prod-lantus-solostar",
    "brandName": "Lantus SoloStar 100 U/mL",
    "genericName": "Insulin Glargine (Long-Acting Analog)",
    "activeIngredients": "Insulin glargine 100 units/mL solution in a 3mL pre-filled SoloStar pen",
    "packSize": "5 x 3mL Pre-filled Pens",
    "schedule": "S4",
    "categoryId": "cat-4",
    "categoryFa": "بیماری‌های غدد، متابولیسم و استخوان (Endocrine & Metabolic)",
    "categoryEn": "Endocrine, Bone & Metabolic Diseases",
    "subcategoryId": "sub-4-1",
    "subcategoryFa": "دیابت ملیتوس، انسولین و داروهای قند خون (Diabetes Mellitus)",
    "subcategoryEn": "Diabetes Mellitus, Insulin, SGLT2i & GLP-1",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-novorapid-flexpen",
    "documentId": "doc-product-prod-novorapid-flexpen",
    "brandName": "NovoRapid FlexPen 100 U/mL",
    "genericName": "Insulin Aspart (Rapid-Acting Analog)",
    "activeIngredients": "Insulin aspart 100 units/mL solution in a 3mL FlexPen",
    "packSize": "5 x 3mL Pre-filled FlexPens",
    "schedule": "S4",
    "categoryId": "cat-4",
    "categoryFa": "بیماری‌های غدد، متابولیسم و استخوان (Endocrine & Metabolic)",
    "categoryEn": "Endocrine, Bone & Metabolic Diseases",
    "subcategoryId": "sub-4-1",
    "subcategoryFa": "دیابت ملیتوس، انسولین و داروهای قند خون (Diabetes Mellitus)",
    "subcategoryEn": "Diabetes Mellitus, Insulin, SGLT2i & GLP-1",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-fosamax-70mg-once-weekly",
    "documentId": "doc-product-prod-fosamax-70mg-once-weekly",
    "brandName": "Fosamax 70mg Once Weekly",
    "genericName": "Alendronate Sodium",
    "activeIngredients": "Alendronate Sodium 70mg tablet",
    "packSize": "4 Tablets",
    "schedule": "S4",
    "categoryId": "cat-4",
    "categoryFa": "بیماری‌های غدد، متابولیسم و استخوان (Endocrine & Metabolic)",
    "categoryEn": "Endocrine, Bone & Metabolic Diseases",
    "subcategoryId": "sub-4-2",
    "subcategoryFa": "پوکی استخوان و متابولیسم استخوان (Osteoporosis & Bone Metabolism)",
    "subcategoryEn": "Osteoporosis & Bone Metabolism",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-prolia-60mg-syringe",
    "documentId": "doc-product-prod-prolia-60mg-syringe",
    "brandName": "Prolia 60mg Pre-filled Syringe",
    "genericName": "Denosumab",
    "activeIngredients": "Denosumab 60mg in 1.0 mL solution for injection",
    "packSize": "1 Pre-filled Syringe with needle guard",
    "schedule": "S4",
    "categoryId": "cat-4",
    "categoryFa": "بیماری‌های غدد، متابولیسم و استخوان (Endocrine & Metabolic)",
    "categoryEn": "Endocrine, Bone & Metabolic Diseases",
    "subcategoryId": "sub-4-2",
    "subcategoryFa": "پوکی استخوان و متابولیسم استخوان (Osteoporosis & Bone Metabolism)",
    "subcategoryEn": "Osteoporosis & Bone Metabolism",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-actonel-35mg",
    "documentId": "doc-product-prod-actonel-35mg",
    "brandName": "Actonel 35mg Once-a-Week",
    "genericName": "Risedronate Sodium",
    "activeIngredients": "Risedronate Sodium 35mg film-coated tablet",
    "packSize": "4 Tablets",
    "schedule": "S4",
    "categoryId": "cat-4",
    "categoryFa": "بیماری‌های غدد، متابولیسم و استخوان (Endocrine & Metabolic)",
    "categoryEn": "Endocrine, Bone & Metabolic Diseases",
    "subcategoryId": "sub-4-2",
    "subcategoryFa": "پوکی استخوان و متابولیسم استخوان (Osteoporosis & Bone Metabolism)",
    "subcategoryEn": "Osteoporosis & Bone Metabolism",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-caltrate-vitd-plus",
    "documentId": "doc-product-prod-caltrate-vitd-plus",
    "brandName": "Caltrate + Minerals & Vitamin D 1000IU",
    "genericName": "Calcium Carbonate + Colecalciferol",
    "activeIngredients": "Calcium Carbonate 1500mg (equiv. elemental calcium 600mg) + Colecalciferol 25 mcg (1000 IU)",
    "packSize": "100 Tablets",
    "schedule": "Unscheduled",
    "categoryId": "cat-4",
    "categoryFa": "بیماری‌های غدد، متابولیسم و استخوان (Endocrine & Metabolic)",
    "categoryEn": "Endocrine, Bone & Metabolic Diseases",
    "subcategoryId": "sub-4-2",
    "subcategoryFa": "پوکی استخوان و متابولیسم استخوان (Osteoporosis & Bone Metabolism)",
    "subcategoryEn": "Osteoporosis & Bone Metabolism",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-eutroxsig-100mcg",
    "documentId": "doc-product-prod-eutroxsig-100mcg",
    "brandName": "Eutroxsig 100mcg",
    "genericName": "Levothyroxine Sodium",
    "activeIngredients": "Levothyroxine Sodium 100 micrograms tablet",
    "packSize": "200 Tablets",
    "schedule": "S4",
    "categoryId": "cat-4",
    "categoryFa": "بیماری‌های غدد، متابولیسم و استخوان (Endocrine & Metabolic)",
    "categoryEn": "Endocrine, Bone & Metabolic Diseases",
    "subcategoryId": "sub-4-3",
    "subcategoryFa": "اختلالات تیروئید و درمان جایگزینی هورمون (Thyroid Disorders)",
    "subcategoryEn": "Thyroid Disorders & Hormone Replacement",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-oroxine-100mcg",
    "documentId": "doc-product-prod-oroxine-100mcg",
    "brandName": "Oroxine 100mcg",
    "genericName": "Levothyroxine Sodium",
    "activeIngredients": "Levothyroxine Sodium 100 micrograms tablet",
    "packSize": "200 Tablets",
    "schedule": "S4",
    "categoryId": "cat-4",
    "categoryFa": "بیماری‌های غدد، متابولیسم و استخوان (Endocrine & Metabolic)",
    "categoryEn": "Endocrine, Bone & Metabolic Diseases",
    "subcategoryId": "sub-4-3",
    "subcategoryFa": "اختلالات تیروئید و درمان جایگزینی هورمون (Thyroid Disorders)",
    "subcategoryEn": "Thyroid Disorders & Hormone Replacement",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-neo-mercazole-5mg",
    "documentId": "doc-product-prod-neo-mercazole-5mg",
    "brandName": "Neo-Mercazole 5mg",
    "genericName": "Carbimazole",
    "activeIngredients": "Carbimazole 5mg tablet",
    "packSize": "100 Tablets",
    "schedule": "S4",
    "categoryId": "cat-4",
    "categoryFa": "بیماری‌های غدد، متابولیسم و استخوان (Endocrine & Metabolic)",
    "categoryEn": "Endocrine, Bone & Metabolic Diseases",
    "subcategoryId": "sub-4-3",
    "subcategoryFa": "اختلالات تیروئید و درمان جایگزینی هورمون (Thyroid Disorders)",
    "subcategoryEn": "Thyroid Disorders & Hormone Replacement",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-flopen-500mg",
    "documentId": "doc-product-prod-flopen-500mg",
    "brandName": "Flopen 500mg",
    "genericName": "Flucloxacillin Sodium",
    "activeIngredients": "Flucloxacillin Sodium 500mg capsule",
    "packSize": "24 Capsules",
    "schedule": "S4",
    "categoryId": "cat-5",
    "categoryFa": "داروهای ضدعفونت و ایمن‌سازی (Anti-Infectives & Immunisation)",
    "categoryEn": "Anti-Infectives & Immunisation",
    "subcategoryId": "sub-5-1",
    "subcategoryFa": "آنتی‌بیوتیک‌های باکتریایی (Antibacterial Agents)",
    "subcategoryEn": "Antibacterial Agents (Penicillins, Cephalosporins, Macrolides)",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-augmentin-duo-forte",
    "documentId": "doc-product-prod-augmentin-duo-forte",
    "brandName": "Augmentin Duo Forte 875/125mg",
    "genericName": "Amoxicillin + Clavulanic Acid",
    "activeIngredients": "Amoxicillin 875mg + Clavulanic Acid (as potassium clavulanate) 125mg tablet",
    "packSize": "10 Tablets",
    "schedule": "S4",
    "categoryId": "cat-5",
    "categoryFa": "داروهای ضدعفونت و ایمن‌سازی (Anti-Infectives & Immunisation)",
    "categoryEn": "Anti-Infectives & Immunisation",
    "subcategoryId": "sub-5-1",
    "subcategoryFa": "آنتی‌بیوتیک‌های باکتریایی (Antibacterial Agents)",
    "subcategoryEn": "Antibacterial Agents (Penicillins, Cephalosporins, Macrolides)",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-keflex-500mg",
    "documentId": "doc-product-prod-keflex-500mg",
    "brandName": "Keflex 500mg",
    "genericName": "Cephalexin",
    "activeIngredients": "Cephalexin 500mg capsule",
    "packSize": "20 Capsules",
    "schedule": "S4",
    "categoryId": "cat-5",
    "categoryFa": "داروهای ضدعفونت و ایمن‌سازی (Anti-Infectives & Immunisation)",
    "categoryEn": "Anti-Infectives & Immunisation",
    "subcategoryId": "sub-5-1",
    "subcategoryFa": "آنتی‌بیوتیک‌های باکتریایی (Antibacterial Agents)",
    "subcategoryEn": "Antibacterial Agents (Penicillins, Cephalosporins, Macrolides)",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-doryx-100mg",
    "documentId": "doc-product-prod-doryx-100mg",
    "brandName": "Doryx 100mg",
    "genericName": "Doxycycline Hyclate",
    "activeIngredients": "Doxycycline (as hyclate modified-release pellets) 100mg tablet",
    "packSize": "21 Tablets",
    "schedule": "S4",
    "categoryId": "cat-5",
    "categoryFa": "داروهای ضدعفونت و ایمن‌سازی (Anti-Infectives & Immunisation)",
    "categoryEn": "Anti-Infectives & Immunisation",
    "subcategoryId": "sub-5-1",
    "subcategoryFa": "آنتی‌بیوتیک‌های باکتریایی (Antibacterial Agents)",
    "subcategoryEn": "Antibacterial Agents (Penicillins, Cephalosporins, Macrolides)",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-klacid-250mg",
    "documentId": "doc-product-prod-klacid-250mg",
    "brandName": "Klacid 250mg",
    "genericName": "Clarithromycin",
    "activeIngredients": "Clarithromycin 250mg tablet",
    "packSize": "14 Tablets",
    "schedule": "S4",
    "categoryId": "cat-5",
    "categoryFa": "داروهای ضدعفونت و ایمن‌سازی (Anti-Infectives & Immunisation)",
    "categoryEn": "Anti-Infectives & Immunisation",
    "subcategoryId": "sub-5-1",
    "subcategoryFa": "آنتی‌بیوتیک‌های باکتریایی (Antibacterial Agents)",
    "subcategoryEn": "Antibacterial Agents (Penicillins, Cephalosporins, Macrolides)",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-flagyl-400mg",
    "documentId": "doc-product-prod-flagyl-400mg",
    "brandName": "Flagyl 400mg",
    "genericName": "Metronidazole",
    "activeIngredients": "Metronidazole 400mg tablet",
    "packSize": "21 Tablets",
    "schedule": "S4",
    "categoryId": "cat-5",
    "categoryFa": "داروهای ضدعفونت و ایمن‌سازی (Anti-Infectives & Immunisation)",
    "categoryEn": "Anti-Infectives & Immunisation",
    "subcategoryId": "sub-5-1",
    "subcategoryFa": "آنتی‌بیوتیک‌های باکتریایی (Antibacterial Agents)",
    "subcategoryEn": "Antibacterial Agents (Penicillins, Cephalosporins, Macrolides)",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-valtrex-500mg",
    "documentId": "doc-product-prod-valtrex-500mg",
    "brandName": "Valtrex 500mg",
    "genericName": "Valaciclovir",
    "activeIngredients": "Valaciclovir Hydrochloride 500mg tablet",
    "packSize": "30 Tablets",
    "schedule": "S4",
    "categoryId": "cat-5",
    "categoryFa": "داروهای ضدعفونت و ایمن‌سازی (Anti-Infectives & Immunisation)",
    "categoryEn": "Anti-Infectives & Immunisation",
    "subcategoryId": "sub-5-2",
    "subcategoryFa": "داروهای ضدویروس و واکسن‌ها (Antivirals & Immunisation)",
    "subcategoryEn": "Antiviral Agents & Vaccines",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-tamiflu-75mg",
    "documentId": "doc-product-prod-tamiflu-75mg",
    "brandName": "Tamiflu 75mg",
    "genericName": "Oseltamivir Phosphate",
    "activeIngredients": "Oseltamivir Phosphate 75mg capsule",
    "packSize": "10 Capsules",
    "schedule": "S4",
    "categoryId": "cat-5",
    "categoryFa": "داروهای ضدعفونت و ایمن‌سازی (Anti-Infectives & Immunisation)",
    "categoryEn": "Anti-Infectives & Immunisation",
    "subcategoryId": "sub-5-2",
    "subcategoryFa": "داروهای ضدویروس و واکسن‌ها (Antivirals & Immunisation)",
    "subcategoryEn": "Antiviral Agents & Vaccines",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-shingrix-vaccine",
    "documentId": "doc-product-prod-shingrix-vaccine",
    "brandName": "Shingrix Adjuvanted Vaccine",
    "genericName": "Recombinant Varicella Zoster Virus Glycoprotein E Vaccine",
    "activeIngredients": "Recombinant VZV glycoprotein E (50 mcg) with AS01B adjuvant system (2-vial kit)",
    "packSize": "1 Dose Kit (Antigen vial + Adjuvant vial)",
    "schedule": "S4",
    "categoryId": "cat-5",
    "categoryFa": "داروهای ضدعفونت و ایمن‌سازی (Anti-Infectives & Immunisation)",
    "categoryEn": "Anti-Infectives & Immunisation",
    "subcategoryId": "sub-5-2",
    "subcategoryFa": "داروهای ضدویروس و واکسن‌ها (Antivirals & Immunisation)",
    "subcategoryEn": "Antiviral Agents & Vaccines",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-fluvax-quadrivalent",
    "documentId": "doc-product-prod-fluvax-quadrivalent",
    "brandName": "FluQuadri / Fluarix Tetra (Inactivated Quadrivalent Influenza Vaccine)",
    "genericName": "Influenza Virus Vaccine (Surface Antigen / Split Virion, Inactivated)",
    "activeIngredients": "Quadrivalent inactivated influenza surface antigens (60 mcg total HA, 15 mcg per each of 4 strains)",
    "packSize": "1 Pre-filled Syringe 0.5 mL",
    "schedule": "S4",
    "categoryId": "cat-5",
    "categoryFa": "داروهای ضدعفونت و ایمن‌سازی (Anti-Infectives & Immunisation)",
    "categoryEn": "Anti-Infectives & Immunisation",
    "subcategoryId": "sub-5-2",
    "subcategoryFa": "داروهای ضدویروس و واکسن‌ها (Antivirals & Immunisation)",
    "subcategoryEn": "Antiviral Agents & Vaccines",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-rectogesic-gtn",
    "documentId": "doc-product-prod-rectogesic-gtn",
    "brandName": "Rectogesic 0.2% Rectal Ointment",
    "genericName": "Glyceryl Trinitrate (GTN) 0.2%",
    "activeIngredients": "Glyceryl trinitrate 2mg/g (0.2% w/w) in paraffin base",
    "packSize": "30g Tube with measuring guide",
    "schedule": "S3",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-4",
    "subcategoryFa": "دستگاه تنفس، سرماخوردگی، سرفه و آلرژی (Respiratory & Allergy)",
    "subcategoryEn": "Respiratory, Cough, Cold & Allergy",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-proctosedyl-oint",
    "documentId": "doc-product-prod-proctosedyl-oint",
    "brandName": "Proctosedyl Ointment / Suppositories",
    "genericName": "Hydrocortisone 5mg/g + Cinchocaine HCl 5mg/g",
    "activeIngredients": "Hydrocortisone 0.5% + Cinchocaine hydrochloride 0.5%",
    "packSize": "30g Tube / 12 Suppositories",
    "schedule": "S2",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-4",
    "subcategoryFa": "دستگاه تنفس، سرماخوردگی، سرفه و آلرژی (Respiratory & Allergy)",
    "subcategoryEn": "Respiratory, Cough, Cold & Allergy",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-benzac-ac-wash",
    "documentId": "doc-product-prod-benzac-ac-wash",
    "brandName": "Benzac AC 5% Wash / Gel",
    "genericName": "Benzoyl Peroxide 5%",
    "activeIngredients": "Benzoyl peroxide 50mg/g (5% w/w) in water-based gel/wash",
    "packSize": "200mL Wash / 50g Gel",
    "schedule": "Unscheduled",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-5",
    "subcategoryFa": "دستگاه گوارش، اسید معده، ریفلاکس، یبوست و اسهال (Gastrointestinal)",
    "subcategoryEn": "Gastrointestinal, Acid, IBS, Constipation & Diarrhea",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-azclear-lotion",
    "documentId": "doc-product-prod-azclear-lotion",
    "brandName": "Azclear Action Medicated Lotion 20%",
    "genericName": "Azelaic Acid 20%",
    "activeIngredients": "Azelaic acid 200mg/g (20% w/w)",
    "packSize": "25g Tube",
    "schedule": "S2",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-5",
    "subcategoryFa": "دستگاه گوارش، اسید معده، ریفلاکس، یبوست و اسهال (Gastrointestinal)",
    "subcategoryEn": "Gastrointestinal, Acid, IBS, Constipation & Diarrhea",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-daivobet-gel",
    "documentId": "doc-product-prod-daivobet-gel",
    "brandName": "Daivobet 50/500 Gel / Ointment",
    "genericName": "Calcipotriol 50mcg/g + Betamethasone Dipropionate 500mcg/g",
    "activeIngredients": "Calcipotriol 50 micrograms/g (as monohydrate) + Betamethasone 0.5mg/g (as dipropionate)",
    "packSize": "30g Tube",
    "schedule": "S4",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-5",
    "subcategoryFa": "دستگاه گوارش، اسید معده، ریفلاکس، یبوست و اسهال (Gastrointestinal)",
    "subcategoryEn": "Gastrointestinal, Acid, IBS, Constipation & Diarrhea",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-dymista-spray",
    "documentId": "doc-product-prod-dymista-spray",
    "brandName": "Dymista 125/50 Nasal Spray",
    "genericName": "Azelastine HCl 137mcg + Fluticasone Propionate 50mcg per actuation",
    "activeIngredients": "Azelastine hydrochloride 125 micrograms + Fluticasone propionate 50 micrograms per spray",
    "packSize": "120 Metered Sprays Bottle",
    "schedule": "S4",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-6",
    "subcategoryFa": "مراقبت‌های پوستی، درماتیت و اگزما (Dermatology & Skin Care)",
    "subcategoryEn": "Dermatology, Eczema & Skin Care",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-ventolin-asmol-100",
    "documentId": "doc-product-prod-ventolin-asmol-100",
    "brandName": "Ventolin / Asmol 100mcg CFC-Free Inhaler",
    "genericName": "Salbutamol Sulfate 100mcg/actuation",
    "activeIngredients": "Salbutamol sulfate 100 micrograms per metered actuation",
    "packSize": "200 Metered Inhalations (MDI)",
    "schedule": "S3",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-6",
    "subcategoryFa": "مراقبت‌های پوستی، درماتیت و اگزما (Dermatology & Skin Care)",
    "subcategoryEn": "Dermatology, Eczema & Skin Care",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-colgout-tablets",
    "documentId": "doc-product-prod-colgout-tablets",
    "brandName": "Colgout 500mcg Tablets",
    "genericName": "Colchicine 500mcg",
    "activeIngredients": "Colchicine 500 micrograms per tablet",
    "packSize": "30 Tablets",
    "schedule": "S4",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-1",
    "subcategoryFa": "ضد درد و تب (Analgesics & Antipyretics)",
    "subcategoryEn": "Analgesics & Antipyretics",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-allosig-tablets",
    "documentId": "doc-product-prod-allosig-tablets",
    "brandName": "Allosig / Zyloprim (Allopurinol 100mg / 300mg)",
    "genericName": "Allopurinol",
    "activeIngredients": "Allopurinol 100mg or 300mg tablets",
    "packSize": "60 Tablets",
    "schedule": "S4",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-1",
    "subcategoryFa": "ضد درد و تب (Analgesics & Antipyretics)",
    "subcategoryEn": "Analgesics & Antipyretics",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-nexium-24hr-28tab",
    "documentId": "doc-product-prod-nexium-24hr-28tab",
    "brandName": "Nexium 24HR 20mg Tablets",
    "genericName": "Esomeprazole 20mg (as magnesium trihydrate)",
    "activeIngredients": "Esomeprazole 20mg enteric-coated tablets",
    "packSize": "14 Tablets (S2) / 28 Tablets (S3)",
    "schedule": "S3",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-4",
    "subcategoryFa": "دستگاه تنفس، سرماخوردگی، سرفه و آلرژی (Respiratory & Allergy)",
    "subcategoryEn": "Respiratory, Cough, Cold & Allergy",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  },
  {
    "id": "prod-canesten-once",
    "documentId": "doc-product-prod-canesten-once",
    "brandName": "Canesten Once 500mg Pessary + 1% Cream",
    "genericName": "Clotrimazole 500mg Pessary",
    "activeIngredients": "Clotrimazole 500mg vaginal pessary + Clotrimazole 10mg/g external cream",
    "packSize": "1 Pessary with applicator + 10g Cream",
    "schedule": "S3",
    "categoryId": "cat-1",
    "categoryFa": "مراقبت‌های اولیه، داروهای بدون نسخه و کمک‌های اولیه",
    "categoryEn": "Primary Care, OTC & First Aid",
    "subcategoryId": "sub-1-2",
    "subcategoryFa": "داروهای ضد قارچ و ضد انگل (Antifungals & Anthelmintics)",
    "subcategoryEn": "Antifungal & Anthelmintic Agents",
    "sourceUrl": "https://github.com/hamedharami-hub/pharmacy/blob/5b4f7d2443a3ed97aea752c1d0d18583ce6d0067/data/shelf/shelfProducts.ts",
    "contentReviewStatus": "unreviewed"
  }
];
