import {test} from 'node:test';
import assert from 'node:assert/strict';
import {defaultState,normalizeState,storageKey,loadState,restoreState,trustedMessage} from '../public/caravan/state.js';
import {performTransfer,replayTransfers,hasPendingTransfers} from '../public/caravan/transactions.js';
const memory=()=>{const map=new Map();return {getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,String(v)),map};};
const fixture=()=>{const storage=memory(),owner='alice';const state={...defaultState(owner),essence:100};storage.setItem(storageKey(owner),JSON.stringify(state));let garden={waterDrops:100,sunEnergy:30,focusBlossoms:10,totalHarvests:0};return {storage,owner,readGarden:()=>garden,writeGarden:g=>{garden=g;}};};
const hybrid={id:'hybrid_1',name:'گل نور',stage:3,primary:'angel',secondary:'coder',color:'#123456',secondaryColor:'#abcdef',createdAt:1791180000000,traits:{resonance:'432 Hz'}};
test('v1 migration keeps nested progress, dates, coordinates and legitimate zeros',()=>{
 const raw={...defaultState('alice'),version:1,plants:[{id:'p1',species:'rose',col:2,row:2,plantedAt:1791180000000,boostMs:1,lastWaterAt:1}],decorations:[{district:'grove',slot:0,kind:'arbor'}],synthesizedHybrids:[hybrid],activeHybridId:hybrid.id,cosmicStructures:['gor_totem'],powerAngel:0,soulBond:0};
 const s=normalizeState(raw,'alice');assert.equal(s.version,2);assert.equal(s.plants[0].plantedAt,raw.plants[0].plantedAt);assert.deepEqual(s.decorations,raw.decorations);assert.equal(s.synthesizedHybrids[0].createdAt,hybrid.createdAt);assert.equal(s.powerAngel,0);assert.equal(s.soulBond,0);assert.equal(s.activeHybridId,hybrid.id);
});
test('wrong owner and corrupt saves are rejected; raw recovery copy retained',()=>{const storage=memory();storage.setItem(storageKey('alice'),'{broken');assert.throws(()=>loadState(storage,'alice'));assert.ok([...storage.map.keys()].some(k=>k.includes('recovery')));assert.throws(()=>normalizeState(defaultState('bob'),'alice'));});
test('same transfer twice debits and credits once, preserving unrelated garden fields',()=>{const opts=fixture();opts.writeGarden({...opts.readGarden(),extra:'keep'});const request={...opts,id:'op1',action:'convert-sun'};performTransfer(request);performTransfer(request);assert.equal(opts.readGarden().sunEnergy,20);assert.equal(opts.readGarden().extra,'keep');assert.equal(loadState(opts.storage,opts.owner).essence,110);assert.throws(()=>performTransfer({...request,action:'convert-water'}));});
test('interruption after garden debit is recoverable without second debit',()=>{const opts=fixture(),set=opts.storage.setItem;let fail=true;opts.storage.setItem=(key,value)=>{if(fail&&key===storageKey(opts.owner)&&JSON.parse(value).appliedTransfers?.includes('op2'))throw new Error('interrupted');set(key,value);};assert.throws(()=>performTransfer({...opts,id:'op2',action:'convert-sun'}));assert.equal(opts.readGarden().sunEnergy,20);assert.ok(hasPendingTransfers(opts.storage,opts.owner));fail=false;replayTransfers(opts);assert.equal(opts.readGarden().sunEnergy,20);assert.equal(loadState(opts.storage,opts.owner).essence,110);assert.equal(hasPendingTransfers(opts.storage,opts.owner),false);});
test('completed journal never rewinds a deliberately restored snapshot',()=>{const opts=fixture();performTransfer({...opts,id:'op3',action:'convert-sun'});restoreState(opts.storage,opts.owner,{...defaultState(opts.owner),essence:7});performTransfer({...opts,id:'op3',action:'convert-sun'});assert.equal(loadState(opts.storage,opts.owner).essence,7);assert.equal(opts.readGarden().sunEnergy,20);});
test('insufficient resources and special ids leave both balances unchanged',()=>{const opts=fixture();opts.writeGarden({...opts.readGarden(),sunEnergy:0});assert.throws(()=>performTransfer({...opts,id:'op4',action:'convert-sun'}));assert.throws(()=>performTransfer({...opts,id:'__proto__',action:'convert-sun'}));assert.equal(loadState(opts.storage,opts.owner).essence,100);assert.equal(opts.readGarden().sunEnergy,0);});
test('hybrid creation, growth and blueprint purchase persist through reload',()=>{const opts=fixture();performTransfer({...opts,id:'new1',action:'create-hybrid',payload:{hybrid}});assert.equal(loadState(opts.storage,opts.owner).synthesizedHybrids[0].stage,1);performTransfer({...opts,id:'grow1',action:'evolve-hybrid',payload:{id:hybrid.id}});performTransfer({...opts,id:'build1',action:'build',payload:{id:'gor_totem'}});const s=loadState(opts.storage,opts.owner);assert.equal(s.synthesizedHybrids[0].stage,2);assert.ok(s.cosmicStructures.includes('gor_totem'));assert.equal(s.essence,85);assert.equal(opts.readGarden().waterDrops,90);});
test('restore milestone has a stable world id and pays only once',()=>{const opts=fixture();const s=loadState(opts.storage,opts.owner);opts.storage.setItem(storageKey(opts.owner),JSON.stringify({...s,collected:['seed','crystal','feather'],invention:'lantern',restored:true}));const request={...opts,id:`restore:${s.worldSeed}`,action:'restore-reward'};performTransfer(request);performTransfer(request);assert.equal(opts.readGarden().waterDrops,150);assert.equal(opts.readGarden().totalHarvests,1);});
test('spoofed bridge sender or origin is rejected',()=>{const parent={};assert.ok(trustedMessage({source:parent,origin:'https://example.com',data:{bridgeVersion:1}},parent,'https://example.com'));assert.equal(trustedMessage({source:{},origin:'https://example.com',data:{bridgeVersion:1}},parent,'https://example.com'),false);assert.equal(trustedMessage({source:parent,origin:'https://evil.com',data:{bridgeVersion:1}},parent,'https://example.com'),false);});

test('conversion at essence capacity does not debit resources',()=>{const opts=fixture();opts.storage.setItem(storageKey(opts.owner),JSON.stringify({...defaultState(opts.owner),essence:100000}));assert.throws(()=>performTransfer({...opts,id:'capacity1',action:'convert-sun'}));assert.equal(opts.readGarden().sunEnergy,30);assert.equal(loadState(opts.storage,opts.owner).essence,100000);});
